trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: terraform-secrets

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '20.10.x'
  displayName: 'Install Docker'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'version'
  displayName: 'Check Docker Compose version'

- script: |
    echo "AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)" >> .env
    echo "AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)" >> .env
    echo "AWS_DEFAULT_REGION=$(AWS_DEFAULT_REGION)" >> .env
  displayName: 'Set AWS credentials'

- script: |
    docker-compose run --rm terraform init
  displayName: 'Terraform Init'

- script: |
    docker-compose run --rm terraform plan -out=tfplan
  displayName: 'Terraform Plan'

- script: |
    docker-compose run --rm terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'