FROM python:3.9.20-slim-bullseye

# Install sys packages
RUN apt-get update && \
		apt-get install -y --no-install-recommends \
		gcc \
		libffi-dev \
		libssl-dev \
		&& apt-get clean \
		&& rm -rf /var/lib/apt/lists/*

# install ansible [core 2.15.12]
RUN python3 -m pip install --no-cache-dir ansible==8.7.0
		

WORKDIR /ansible

ENTRYPOINT ["ansible"]
