version: '3.8'

services:
  terraform:
    image: hashicorp/terraform:1.10.0-alpha20240918
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./terraform:/terraform
    working_dir: /terraform
    entrypoint: ["terraform"]

  ansible:
    build:
      context: .
      dockerfile: Dockerfile-ansible
    volumes:
      - ./ansible:/ansible
    working_dir: /ansible
