version: '3.8'

services:
  terraform:
    image: hashicorp/terraform:1.10.0-alpha20240918
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - ./terraform:/terraform
      - ./ansible:/ansible
      - ./key:/root/.ssh:ro
      - ./output:/output
    working_dir: /terraform
    entrypoint: ["terraform"]
    
  tflint:
    build:
      context: .
      dockerfile: ./containers/tflint.Dockerfile
    volumes:
      - ./config:/config:ro
      - ./terraform:/terraform:ro
    working_dir: /
    entrypoint: ["tflint"]

  ansible:
    build:
      context: .
      dockerfile: ./containers/ansible.Dockerfile
    volumes:
      - ./ansible:/ansible
      - ./output:/output
    working_dir: /ansible