---
- name: Update all packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_only: yes

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Create Hello World HTML file
  ansible.builtin.copy:
    content: "<html><body><h1>Hello, World! Created by norice2000</h1></body></html>"
    dest: /usr/share/nginx/html/index.html

- name: Configure Nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart Nginx

- name: Start Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Ensure Nginx is running
  ansible.builtin.service:
    name: nginx
    state: restarted
